
version: '3'
services:
  backend:
        build: ./backend
        ports:
          - 8081:8081
        entrypoint: ["java", "-jar", "-Dspring.profiles.active=dev", "demo_backend.jar"]
  frontend:
        build: ./frontend
        ports:
            - 80:80